### PR TITLE
Add `skipToNextLineOnError` option

### PR DESCRIPTION
**Pull request by karlbecker**
per this comment: https://github.com/wdavidw/node-csv/issues/214#issuecomment-237851703

This currently just has the js modifications - needs some coffee script changes before we can make a PR to merge it back into the main repo.

### CODE REVIEW

**Comment by wdavidw** [comment]
thanks karl. I will need once testcase/sample illustrating the issue. For exemple, it doesnt solve the following test:

``` coffeee

it.skip 'with invalid quotes', (next) ->
  parse """
  "abc","123"x
  "def","456"
  """, jump_to_next_line_on_error: true, (err, data) ->
    (err is null).should.be.true()
    data.length.should.eql 2
    next()
```

**Comment by karlbecker** [comment]
You bet @wdavidw - thanks!  

Sorry, I didn't want this PR to ping you yet; I still need to update the Coffeescript, add tests, etc.  Haven't looked at any of that yet.

I just made this commit so I can start using this workaround now, since it's definitely solving some problems we have.  

I don't know Coffeescript much, but should `jump_to_next_line_on_error` be `skipToNextLineOnError` or `skip_to_next_line_on_error` maybe?

**Comment by wdavidw** [comment]
I rename `skipToNextLineOnError` to `jump_to_next_line_on_error`. coffeescript doesnt truncate the code. It's me who voluntary change the naming convention to underscore, as for all the options (with the exception of rowDelimiter).

**Comment by wdavidw** [comment]
Your code is solving some situation, i'll be interested to get a testcase/sample of it. However, it cant address the testcase I provided above. Solving this is much more complicated as it involved disabling the ability to support a value of "rowDelimiter" inside a field. If not, how to determine an open quoted field isnt close unless we reach the end of the dataset.

**Comment by justinmchase** [comment]
It would be nice to get some progress on this, I have some bad files I have to deal with :(

**Comment by wdavidw** [comment]
A few test cases would help

**Comment by justinmchase** [comment]
I don't know how to write this optimally in coffeescript but here is a test for my current problem:

```js
it('stream skips row with invalid quoted column', done => {
  const r = new Readable()
  r._read = () => { }
  r.push('"a","b","c"\n')
  r.push('"one","two","three"\n')
  r.push('"four",""","six"\n') // bad quoting on inner column
  r.push('"seven","eight","nine"\n')
  r.push(null)
  const stream = r.pipe(parse({ skipRowOnError: true }))
  const num = 0
  const errs = 0
  stream.on('data', data => num++)
  stream.on('error', err => errs++)
  stream.on('end', () => {
    expect(num).to.equal(2)
    expect(errs).to.equal(1)
    done()
  })
})
```

**Comment by wdavidw** [comment]
Thank you, your tests could be written as:

```coffee
parse """
"a","b","c"
"one","two","three"
"four",""","six"
"seven","eight","nine"
""", (err, result) ->
  result.should.eql [
    ["a","b","c"]
    ["one","two","three"]
    ["seven","eight","nine"]
  ]
```
Do we confirm that would be the expected behavior of the "skipRowOnError" option ?

**Comment by mike-lang** [comment]
@wdavidw - that looks like behavior I would expect and I believe in line with what we were intending when we started this patch.  Reviewing the code, it does look like the name of the option would suggest errors like those thrown [here](https://github.com/thirdiron/node-csv-parse/pull/1/files#diff-6d186b954a58d5bb740f73d84fe39073R384) would also cause a line to be skipped, but apparently we don't accomodate that yet.  @karlbecker - does that look accurate to you?

**Comment by justinmchase** [comment]
Would you still be able to subscribe to `.on('error', ...)`?

**Comment by karlbecker** [comment]
> that looks like behavior I would expect and I believe in line with what we were intending when we started this patch. 

Agreed!

> Reviewing the code, it does look like the name of the option would suggest errors like those thrown [here](https://github.com/thirdiron/node-csv-parse/pull/1/files#diff-6d186b954a58d5bb740f73d84fe39073R384) would also cause a line to be skipped, but apparently we don't accomodate that yet. @karlbecker - does that look accurate to you?

Also agreed. Another test case can cover that.

(note - to get [the link above](https://github.com/thirdiron/node-csv-parse/pull/1/files#diff-6d186b954a58d5bb740f73d84fe39073R384) to show the line @mike-lang mentions, show some of the lines hidden in GitHub's default UI)

> Would you still be able to subscribe to .on('error', ...)?

@justinmchase , would you like that to still happen? I think since we're not throwing an error, it won't do it, but haven't tried it out.  Feel free to modify this to bring that behavior back!

**Comment by wdavidw** [comment]
> Would you still be able to subscribe to .on('error', ...)?

I'll rather have a new event, like `on('skip', ...)`. On error in the Event API is tied to error throwing.

**Comment by wdavidw** [comment]
Latest [commit](https://github.com/adaltas/node-csv-parse/commit/3beaa46b42187eec98b01efd28710205bb3c5255) should implement the functionnality. Please share your comments if any.

**Comment by karlbecker** [comment]
Looks like your recent change addresses this case and a handful of other cases this change didn't address, @wdavidw - bravo! 👏 

One thought: seems like this little chunk of code [starting here with `unless`](https://github.com/adaltas/node-csv-parse/commit/3beaa46b42187eec98b01efd28710205bb3c5255#diff-f35c5932bb4da98c9da8192a6851d827R183) is repeated in many places:
```
          err = Error "Quoted field not terminated at line #{@lines+1}"
          unless @options.skip_lines_with_error
            return err
          else
            @emit 'skip', err
            return
```

Since it's sprinkled throughout the code base, maybe it could be DRYed up into a function that is passed the `err` object?

Otherwise seems like it should address the issue we were trying to solve, yes! 🙌

**Comment by wdavidw** [comment]
Concerning your comment

> One thought: seems like this little chunk of code starting here with unless is repeated in many places

I was thinking about but was lacking some courage, thanks for the [inspiration](https://github.com/adaltas/node-csv-parse/commit/ed9d2a5f8fe93a6944e6bc8a787672dc52b09999).

**Comment by wdavidw** [comment]
A new version 2.1.0 is published.

**Comment by karlbecker** [comment]
Thanks again for publishing the new version, @wdavidw ! Going to close out this branch's PR here.

**Pull request closed without merging**
